export enum ComponentType {
  HERO = 'HERO',
  IMAGE = 'IMAGE',
  CODE = 'CODE',
  NEXT_ARTICLE = 'NEXT_ARTICLE',
  TIME_LINE = 'TIME_LINE',
  DETAILS = 'DETAILS',
  QUOTE = 'QUOTE',
  TEXT_EDITOR = 'TEXT',
  IMAGE_CAPTION = 'IMAGE_CAPTION',
  STATS = 'STATS',
  QUESTIONS = 'QUESTIONS',
  HEADER = 'HEADER',
}
